/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "tx_int.h"
#include "rx_int.h"
#include "Dial.h"
#include "enc_a_aliases.h"
#include "enc_a.h"
#include "Clock_1.h"
#include "enc_b_aliases.h"
#include "enc_b.h"
#include "enc_sw_aliases.h"
#include "enc_sw.h"
#include "enc_sw_int.h"
#include "I2COLED.h"
#include "I2COLED_PVT.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "Em_EEPROM_1.h"
#include "USBFS_1.h"
#include "USBFS_1_audio.h"
#include "USBFS_1_cdc.h"
#include "USBFS_1_hid.h"
#include "USBFS_1_midi.h"
#include "USBFS_1_pvt.h"
#include "USBFS_1_cydmac.h"
#include "USBFS_1_msc.h"
#include "LED_aliases.h"
#include "LED.h"
#include "sw1_aliases.h"
#include "sw1.h"
#include "sw1_int.h"
#include "SDA_RTC_aliases.h"
#include "SDA_RTC.h"
#include "SCL_RTC_aliases.h"
#include "SCL_RTC.h"
#include "I2CRTC.h"
#include "I2CRTC_PVT.h"
#include "PRS.h"
#include "UART_1_IntClock.h"
#include "Dial_Cnt8.h"
#include "USBFS_1_Dm_aliases.h"
#include "USBFS_1_Dm.h"
#include "USBFS_1_Dp_aliases.h"
#include "USBFS_1_Dp.h"
#include "I2CRTC_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

